[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"

[lib]
name = "orderbook"
path = "src/orderbook.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
